#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec2 {
    pub x: f32,
    pub y: f32,
}

impl Vec2 {
    pub const ZERO: Vec2 = Vec2 { x: 0.0, y: 0.0 };

    pub const fn new(x: f32, y: f32) -> Self {
        Self { x, y }
    }

    pub fn length(self) -> f32 {
        (self.x * self.x + self.y * self.y).sqrt()
    }

    pub fn scale(self, s: f32) -> Self {
        Self::new(self.x * s, self.y * s)
    }

    pub fn add(self, other: Self) -> Self {
        Self::new(self.x + other.x, self.y + other.y)
    }

    pub fn sub(self, other: Self) -> Self {
        Self::new(self.x - other.x, self.y - other.y)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Material {
    Air,
    Water,
    Steam,
    Fire,
    Earth,
    Ice,
}

#[derive(Debug, Clone, Copy)]
pub struct MaterialProps {
    pub density: f32,
    pub conductivity: f32,
    pub viscosity: f32,
    pub is_solid: bool,
    pub is_fluid: bool,
    pub equilibrium_temp: f32,
    pub equilibrium_pressure: f32,
    /// Heat generated by this material per tick (K/tick at dt=1). The cell
    /// self-heats up to its equilibrium_temp; diffusion then carries it away.
    /// This is how persistent "mana-fed" sources like Fire stay hot without
    /// needing fuel or unconditional decay.
    pub heat_generation: f32,
}

impl Material {
    pub const fn props(self) -> MaterialProps {
        match self {
            Material::Air => MaterialProps {
                density: 1.2,
                conductivity: 0.3,
                viscosity: 0.02,
                is_solid: false,
                is_fluid: true,
                equilibrium_temp: 293.15,
                equilibrium_pressure: 101_325.0,
                heat_generation: 0.0,
            },
            Material::Water => MaterialProps {
                density: 1000.0,
                conductivity: 0.6,
                viscosity: 0.1,
                is_solid: false,
                is_fluid: true,
                equilibrium_temp: 293.15,
                equilibrium_pressure: 101_325.0,
                heat_generation: 0.0,
            },
            Material::Steam => MaterialProps {
                density: 0.6,
                conductivity: 0.04,
                viscosity: 0.015,
                is_solid: false,
                is_fluid: true,
                equilibrium_temp: 373.15,
                equilibrium_pressure: 101_325.0,
                heat_generation: 0.0,
            },
            Material::Fire => MaterialProps {
                density: 0.3,
                conductivity: 0.08,
                viscosity: 0.01,
                is_solid: false,
                is_fluid: true,
                equilibrium_temp: 1200.0,
                equilibrium_pressure: 101_325.0,
                heat_generation: 20.0,
            },
            Material::Earth => MaterialProps {
                density: 2500.0,
                conductivity: 0.025,
                viscosity: 1.0,
                is_solid: true,
                is_fluid: false,
                equilibrium_temp: 293.15,
                equilibrium_pressure: 101_325.0,
                heat_generation: 0.0,
            },
            Material::Ice => MaterialProps {
                density: 917.0,
                conductivity: 2.2,
                viscosity: 1.0,
                is_solid: true,
                is_fluid: false,
                equilibrium_temp: 263.15,
                equilibrium_pressure: 101_325.0,
                heat_generation: 0.0,
            },
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Cell {
    pub material: Material,
    pub temperature: f32,
    pub pressure: f32,
    pub velocity: Vec2,
    pub density: f32,
    /// Latent-heat buffer at a phase boundary, measured in K-equivalents.
    /// While a cell sits at its phase-change temperature, incoming heat fills
    /// this buffer instead of raising temperature. The material flips only
    /// when the buffer reaches the latent-heat threshold for that transition.
    /// Sign tracks direction: positive = energy toward the hotter phase
    /// (melting / boiling), negative = toward the colder phase (freezing /
    /// condensing). Zero outside of phase boundaries.
    pub phase_energy: f32,
}

impl Cell {
    pub fn new(material: Material) -> Self {
        let p = material.props();
        Self {
            material,
            temperature: p.equilibrium_temp,
            pressure: p.equilibrium_pressure,
            velocity: Vec2::ZERO,
            density: p.density,
            phase_energy: 0.0,
        }
    }

    pub fn with_temperature(mut self, temp: f32) -> Self {
        self.temperature = temp;
        self
    }

    pub fn props(&self) -> MaterialProps {
        self.material.props()
    }
}

impl Default for Cell {
    fn default() -> Self {
        Cell::new(Material::Air)
    }
}
